### ISSUE TITLE
Google voice recognition compatable?

### ISSUE THREAD

**Issue by bcomnes** [kapetan/pcm-stream#1]
I'm trying to use an audio stream from getUserMedia with google's text to speech API inside of an electron app and came across your modules.  They look close to what I want, but they aren't working and I was wonder if you had any insights into why maybe?  

I was able to get a working prototype using an audio stream using the https://github.com/gillesdemey/node-record-lpcm16 module and piping that stream into Google's speech module (Example: https://github.com/bcomnes/speech-test/blob/master/sox_renderer.js)

So I tried something similar using this module but it doesn't seem to work (Example: https://github.com/bcomnes/speech-test/blob/master/renderer.js) 

Any idea what the differences are between the streams produced by Sox + https://github.com/gillesdemey/node-record-lpcm16 and the ones this module puts out?

**Comment by bcomnes** [comment]
Oh wow, never mind. Works great!  Just had the SAMPLE_RATE set wrong in the google speech API request.   Thank you for letting me [rubber duck](https://rubberduckdebugging.com/) your issue thread.

**Comment by kapetan** [comment]
Glad it worked out.
